"""Broker abstraction layer — common interface for all brokers."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class OrderSide(Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"


class OrderStatus(Enum):
    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


@dataclass
class Order:
    ticker: str
    side: OrderSide
    order_type: OrderType
    quantity: float = 0           # shares (int for whole, float for fractional)
    notional_value: float | None = None  # dollar amount — used instead of qty for fractional buys
    limit_price: float | None = None
    stop_price: float | None = None
    trail_pct: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    filled_price: float | None = None
    filled_quantity: float = 0
    broker_order_id: str = ""
    submitted_at: datetime | None = None
    filled_at: datetime | None = None
    # Idempotency/traceability (2026-07-24) -- auto-generated by AlpacaBroker.submit_order
    # if not explicitly set here.
    client_order_id: str | None = None


@dataclass
class AccountInfo:
    cash: float
    portfolio_value: float
    buying_power: float
    equity: float
    last_equity: float = 0.0  # equity at previous day's close — used for daily P/L
    # day_trade_count/pattern_day_trader removed entirely (2026-08-08, GitHub #57) --
    # FINRA retired the PDT rule and Alpaca completely removed these fields (along with
    # daytrading_buying_power/last_daytrade_count/last_daytrading_buying_power) from the
    # real Account API response by 2026-07-06, replaced by the new Intraday Margin
    # Framework. Confirmed against Alpaca's own changelog. Both fields were already dead
    # (zero consumers anywhere in this codebase) before removal, so this closes a real
    # correctness gap without changing any live behavior -- the old getattr(...,
    # default) pattern prevented a crash but silently pinned both values to 0/False
    # forever regardless of the account's true state, which any *future* day-trading-
    # risk logic built on them would have silently and permanently misread.


class Broker(ABC):
    @abstractmethod
    async def connect(self):
        pass

    @abstractmethod
    async def disconnect(self):
        pass

    @abstractmethod
    async def get_account(self) -> AccountInfo:
        pass

    @abstractmethod
    async def submit_order(self, order: Order) -> Order:
        pass

    @abstractmethod
    async def cancel_order(self, broker_order_id: str) -> bool:
        pass

    @abstractmethod
    async def get_order_status(self, broker_order_id: str) -> Order:
        pass

    @abstractmethod
    async def get_positions(self) -> list[dict]:
        pass

    @abstractmethod
    async def get_open_orders(self) -> list[dict]:
        pass

    @abstractmethod
    async def get_quote(self, ticker: str) -> float:
        pass
